# logger
model_name: 'SNN'                       # name of model weight and history file
save_weight: True                       # to save model weight or not
data_path: './data'                     # path of training data

# model
class_num: 10                           # category numbers of the network
sample_time: 30                         # points sample form SNN output neural
conv_layers:
  layer_num: 4                          # how many layers in convolutional layer
  filter_num:                           # filter numbers in each layer
    - 16
    - 16
    - 32
    - 32
  filter_size:                          # filter size in each layers
    - 5
    - 5
    - 3
    - 3

# training setting
epochs: 20                              # maximum number of training epoch
minibatch_size: 1024                    # how many image pass through model when doing a iteration


# optimizer setting
optim:
  name: 'SGD'                           # optimizer selections
  args:                                 # args for each optimizer
    learning_rate: 0.01
    momentum: 0.9
